
USE [master]
GO
-- DROP DATABASE CursoSql

/****** Object:  Database [CursoSql]    Script Date: 18/02/2015 07:41:20 p.m. ******/
CREATE DATABASE [CursoSql] ON  PRIMARY 
( NAME = N'CursoSql', FILENAME = N'd:\sqlserver\express\data\CursoSql.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CursoSql_log', FILENAME = N'd:\sqlserver\express\log\CursoSql_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CursoSql] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CursoSql].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CursoSql] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CursoSql] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CursoSql] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CursoSql] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CursoSql] SET ARITHABORT OFF 
GO

ALTER DATABASE [CursoSql] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CursoSql] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CursoSql] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CursoSql] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CursoSql] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CursoSql] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CursoSql] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CursoSql] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CursoSql] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CursoSql] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CursoSql] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CursoSql] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CursoSql] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CursoSql] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CursoSql] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CursoSql] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CursoSql] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CursoSql] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CursoSql] SET RECOVERY FULL 
GO

ALTER DATABASE [CursoSql] SET  MULTI_USER 
GO

ALTER DATABASE [CursoSql] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CursoSql] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CursoSql] SET  READ_WRITE 
GO

