//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AdventureWorks2008Model", "FK_StateProvince_CountryRegion_CountryRegionCode", "CountryRegion", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdventureWorks2008Model.CountryRegion), "StateProvince", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdventureWorks2008Model.StateProvince))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AdventureWorks2008Model", "FK_Address_StateProvince_StateProvinceID", "StateProvince", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdventureWorks2008Model.StateProvince), "Address", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdventureWorks2008Model.Address))]

// Original file name:
// Generation date: 6/28/2013 10:02:23 PM
namespace AdventureWorks2008Model
{
    
    /// <summary>
    /// There are no comments for AdventureWorks2008Entities in the schema.
    /// </summary>
    public partial class AdventureWorks2008Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new AdventureWorks2008Entities object using the connection string found in the 'AdventureWorks2008Entities' section of the application configuration file.
        /// </summary>
        public AdventureWorks2008Entities() : 
                base("name=AdventureWorks2008Entities", "AdventureWorks2008Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AdventureWorks2008Entities object.
        /// </summary>
        public AdventureWorks2008Entities(string connectionString) : 
                base(connectionString, "AdventureWorks2008Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AdventureWorks2008Entities object.
        /// </summary>
        public AdventureWorks2008Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "AdventureWorks2008Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CountryRegion in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CountryRegion> CountryRegion
        {
            get
            {
                if ((this._CountryRegion == null))
                {
                    this._CountryRegion = base.CreateQuery<CountryRegion>("[CountryRegion]");
                }
                return this._CountryRegion;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CountryRegion> _CountryRegion;
        /// <summary>
        /// There are no comments for StateProvince in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<StateProvince> StateProvince
        {
            get
            {
                if ((this._StateProvince == null))
                {
                    this._StateProvince = base.CreateQuery<StateProvince>("[StateProvince]");
                }
                return this._StateProvince;
            }
        }
        private global::System.Data.Objects.ObjectQuery<StateProvince> _StateProvince;
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Address> Address
        {
            get
            {
                if ((this._Address == null))
                {
                    this._Address = base.CreateQuery<Address>("[Address]");
                }
                return this._Address;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Address> _Address;
        /// <summary>
        /// There are no comments for CountryRegion in the schema.
        /// </summary>
        public void AddToCountryRegion(CountryRegion countryRegion)
        {
            base.AddObject("CountryRegion", countryRegion);
        }
        /// <summary>
        /// There are no comments for StateProvince in the schema.
        /// </summary>
        public void AddToStateProvince(StateProvince stateProvince)
        {
            base.AddObject("StateProvince", stateProvince);
        }
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public void AddToAddress(Address address)
        {
            base.AddObject("Address", address);
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorks2008Model.CountryRegion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CountryRegionCode
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AdventureWorks2008Model", Name="CountryRegion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CountryRegion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CountryRegion object.
        /// </summary>
        /// <param name="countryRegionCode">Initial value of CountryRegionCode.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static CountryRegion CreateCountryRegion(string countryRegionCode, string name, global::System.DateTime modifiedDate)
        {
            CountryRegion countryRegion = new CountryRegion();
            countryRegion.CountryRegionCode = countryRegionCode;
            countryRegion.Name = name;
            countryRegion.ModifiedDate = modifiedDate;
            return countryRegion;
        }
        /// <summary>
        /// There are no comments for Property CountryRegionCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionCode
        {
            get
            {
                return this._CountryRegionCode;
            }
            set
            {
                this.OnCountryRegionCodeChanging(value);
                this.ReportPropertyChanging("CountryRegionCode");
                this._CountryRegionCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CountryRegionCode");
                this.OnCountryRegionCodeChanged();
            }
        }
        private string _CountryRegionCode;
        partial void OnCountryRegionCodeChanging(string value);
        partial void OnCountryRegionCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for StateProvince in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AdventureWorks2008Model", "FK_StateProvince_CountryRegion_CountryRegionCode", "StateProvince")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<StateProvince> StateProvince
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<StateProvince>("AdventureWorks2008Model.FK_StateProvince_CountryRegion_CountryRegionCode", "StateProvince");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<StateProvince>("AdventureWorks2008Model.FK_StateProvince_CountryRegion_CountryRegionCode", "StateProvince", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorks2008Model.StateProvince in the schema.
    /// </summary>
    /// <KeyProperties>
    /// StateProvinceID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AdventureWorks2008Model", Name="StateProvince")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class StateProvince : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new StateProvince object.
        /// </summary>
        /// <param name="stateProvinceID">Initial value of StateProvinceID.</param>
        /// <param name="stateProvinceCode">Initial value of StateProvinceCode.</param>
        /// <param name="isOnlyStateProvinceFlag">Initial value of IsOnlyStateProvinceFlag.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="territoryID">Initial value of TerritoryID.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static StateProvince CreateStateProvince(int stateProvinceID, string stateProvinceCode, bool isOnlyStateProvinceFlag, string name, int territoryID, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            StateProvince stateProvince = new StateProvince();
            stateProvince.StateProvinceID = stateProvinceID;
            stateProvince.StateProvinceCode = stateProvinceCode;
            stateProvince.IsOnlyStateProvinceFlag = isOnlyStateProvinceFlag;
            stateProvince.Name = name;
            stateProvince.TerritoryID = territoryID;
            stateProvince.rowguid = rowguid;
            stateProvince.ModifiedDate = modifiedDate;
            return stateProvince;
        }
        /// <summary>
        /// There are no comments for Property StateProvinceID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int StateProvinceID
        {
            get
            {
                return this._StateProvinceID;
            }
            set
            {
                this.OnStateProvinceIDChanging(value);
                this.ReportPropertyChanging("StateProvinceID");
                this._StateProvinceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StateProvinceID");
                this.OnStateProvinceIDChanged();
            }
        }
        private int _StateProvinceID;
        partial void OnStateProvinceIDChanging(int value);
        partial void OnStateProvinceIDChanged();
        /// <summary>
        /// There are no comments for Property StateProvinceCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvinceCode
        {
            get
            {
                return this._StateProvinceCode;
            }
            set
            {
                this.OnStateProvinceCodeChanging(value);
                this.ReportPropertyChanging("StateProvinceCode");
                this._StateProvinceCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("StateProvinceCode");
                this.OnStateProvinceCodeChanged();
            }
        }
        private string _StateProvinceCode;
        partial void OnStateProvinceCodeChanging(string value);
        partial void OnStateProvinceCodeChanged();
        /// <summary>
        /// There are no comments for Property IsOnlyStateProvinceFlag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnlyStateProvinceFlag
        {
            get
            {
                return this._IsOnlyStateProvinceFlag;
            }
            set
            {
                this.OnIsOnlyStateProvinceFlagChanging(value);
                this.ReportPropertyChanging("IsOnlyStateProvinceFlag");
                this._IsOnlyStateProvinceFlag = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsOnlyStateProvinceFlag");
                this.OnIsOnlyStateProvinceFlagChanged();
            }
        }
        private bool _IsOnlyStateProvinceFlag;
        partial void OnIsOnlyStateProvinceFlagChanging(bool value);
        partial void OnIsOnlyStateProvinceFlagChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property TerritoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TerritoryID
        {
            get
            {
                return this._TerritoryID;
            }
            set
            {
                this.OnTerritoryIDChanging(value);
                this.ReportPropertyChanging("TerritoryID");
                this._TerritoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TerritoryID");
                this.OnTerritoryIDChanged();
            }
        }
        private int _TerritoryID;
        partial void OnTerritoryIDChanging(int value);
        partial void OnTerritoryIDChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this.ReportPropertyChanging("rowguid");
                this._rowguid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("rowguid");
                this.OnrowguidChanged();
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for CountryRegion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AdventureWorks2008Model", "FK_StateProvince_CountryRegion_CountryRegionCode", "CountryRegion")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CountryRegion CountryRegion
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CountryRegion>("AdventureWorks2008Model.FK_StateProvince_CountryRegion_CountryRegionCode", "CountryRegion").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CountryRegion>("AdventureWorks2008Model.FK_StateProvince_CountryRegion_CountryRegionCode", "CountryRegion").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CountryRegion in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CountryRegion> CountryRegionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CountryRegion>("AdventureWorks2008Model.FK_StateProvince_CountryRegion_CountryRegionCode", "CountryRegion");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CountryRegion>("AdventureWorks2008Model.FK_StateProvince_CountryRegion_CountryRegionCode", "CountryRegion", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AdventureWorks2008Model", "FK_Address_StateProvince_StateProvinceID", "Address")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Address> Address
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Address>("AdventureWorks2008Model.FK_Address_StateProvince_StateProvinceID", "Address");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Address>("AdventureWorks2008Model.FK_Address_StateProvince_StateProvinceID", "Address", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AdventureWorks2008Model.Address in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AddressID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AdventureWorks2008Model", Name="Address")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Address : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="addressID">Initial value of AddressID.</param>
        /// <param name="addressLine1">Initial value of AddressLine1.</param>
        /// <param name="city">Initial value of City.</param>
        /// <param name="postalCode">Initial value of PostalCode.</param>
        /// <param name="rowguid">Initial value of rowguid.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        public static Address CreateAddress(int addressID, string addressLine1, string city, string postalCode, global::System.Guid rowguid, global::System.DateTime modifiedDate)
        {
            Address address = new Address();
            address.AddressID = addressID;
            address.AddressLine1 = addressLine1;
            address.City = city;
            address.PostalCode = postalCode;
            address.rowguid = rowguid;
            address.ModifiedDate = modifiedDate;
            return address;
        }
        /// <summary>
        /// There are no comments for Property AddressID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID
        {
            get
            {
                return this._AddressID;
            }
            set
            {
                this.OnAddressIDChanging(value);
                this.ReportPropertyChanging("AddressID");
                this._AddressID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddressID");
                this.OnAddressIDChanged();
            }
        }
        private int _AddressID;
        partial void OnAddressIDChanging(int value);
        partial void OnAddressIDChanged();
        /// <summary>
        /// There are no comments for Property AddressLine1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this._AddressLine1;
            }
            set
            {
                this.OnAddressLine1Changing(value);
                this.ReportPropertyChanging("AddressLine1");
                this._AddressLine1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AddressLine1");
                this.OnAddressLine1Changed();
            }
        }
        private string _AddressLine1;
        partial void OnAddressLine1Changing(string value);
        partial void OnAddressLine1Changed();
        /// <summary>
        /// There are no comments for Property AddressLine2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this._AddressLine2;
            }
            set
            {
                this.OnAddressLine2Changing(value);
                this.ReportPropertyChanging("AddressLine2");
                this._AddressLine2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AddressLine2");
                this.OnAddressLine2Changed();
            }
        }
        private string _AddressLine2;
        partial void OnAddressLine2Changing(string value);
        partial void OnAddressLine2Changed();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this.ReportPropertyChanging("PostalCode");
                this._PostalCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PostalCode");
                this.OnPostalCodeChanged();
            }
        }
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property rowguid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this.ReportPropertyChanging("rowguid");
                this._rowguid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("rowguid");
                this.OnrowguidChanged();
            }
        }
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for StateProvince in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AdventureWorks2008Model", "FK_Address_StateProvince_StateProvinceID", "StateProvince")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public StateProvince StateProvince
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<StateProvince>("AdventureWorks2008Model.FK_Address_StateProvince_StateProvinceID", "StateProvince").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<StateProvince>("AdventureWorks2008Model.FK_Address_StateProvince_StateProvinceID", "StateProvince").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for StateProvince in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<StateProvince> StateProvinceReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<StateProvince>("AdventureWorks2008Model.FK_Address_StateProvince_StateProvinceID", "StateProvince");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<StateProvince>("AdventureWorks2008Model.FK_Address_StateProvince_StateProvinceID", "StateProvince", value);
                }
            }
        }
    }
}
